baseURL = "https://blog.nidhoggfgg.fun"
languageCode = "zh-cn"
title = "nothing"
theme = "moefox"
Paginate = 5
defaultContentLanguage = "zh-cn"

[permalinks]
    posts = "/post/:slug"
    page = "/:slug"

[params]
    mainSections = ["posts", "docs"]

[languages]
    [languages.en]
        languageName = "English"
        title = "nothing"
        weight = 2

    [languages.zh-cn]
        languageName = "中文"
        title = "nothing"
        weight = 1

[markup.highlight]
    style = "dracula"
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
    guessSyntax = true
    noClasses = false

[markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[frontmatter]
    lastmod = ['lastmod', ':git', ':fileModTime', ':default']
