baseURL = "https://blog.nidhoggfgg.fun"
languageCode = "zh-cn"
title = "nothing"
theme = "moefox"
Paginate = 5
defaultContentLanguage = "zh-cn"
enableGitInfo = true
pygmentsUseClasses=true
pygmentsCodeFences=true

[permalinks]
    posts = "/post/:slug"
    page = "/:slug"

[params]
    mainSections = ["posts"]

    [params.article]
        copyBtn = true
        math = true

[languages]
    [languages.en]
        languageName = "English"
        title = "nothing"
        weight = 2

    [languages.zh-cn]
        languageName = "中文"
        title = "nothing"
        weight = 1

[markup.highlight]
    style = "monokai"
    lineNos = false # if need use hl_lines it cant be true
    guessSyntax = true
    noClasses = false

[markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[markup.goldmark.renderer]
    unsafe = true # for using html in markdown

[frontmatter]
    lastmod = [':git', 'lastmod', ':fileModTime', ':default']
